### ISSUE TITLE
Follow PEP 8 Style Guide for Python Code

### ISSUE THREAD

**Issue by florrdv** [AchrafYndz/StrongToGymRun#2]
With every open source project, it's important to follow the guidelines set for the relevant programming languages. This will prevent the use of multiple naming conventions when working with collaborators. Please refer to the [Style Guide for Python Code](https://peps.python.org/pep-0008/) for more information.

**Comment by AchrafYndz** [comment]
All changes have been made. Thanks for your contribution.
